name: Integration Tests

on:
  # Run on pushes to main
  push:
    branches: [ main ]
  # Run on any PR
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      APP_CONFIG_YAML: ${{ secrets.APP_CONFIG_YAML }}
      FIREBASE_ACCOUNT_KEY: ${{ secrets.FIREBASE_ACCOUNT_KEY }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      FIREWORKS_API_KEY: ${{ secrets.FIREWORKS_API_KEY }}
      AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run all tests with coverage
      run: |
        pytest --cov=. --cov-report=term-missing -v
        
    - name: Display test summary
      run: |
        echo "::group::Test Summary"
        python -c "
        import json
        from pathlib import Path
        
        report = Path('.coverage')
        if report.exists():
            print('Coverage report available!')
            
        test_report = Path('.pytest_cache/v/cache/lastfailed')
        if test_report.exists():
            data = json.loads(test_report.read_text())
            total = len(list(Path('.').rglob('test_*.py')))
            failed = len(data)
            passed = total - failed
            print(f'\nTest Summary:\nPassed: {passed}/{total}\nFailed: {failed}/{total}')
        else:
            print('All tests passed!')
        "
        echo "::endgroup::"
