global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  # least 'group_wait' to send the initial notification.
  # This way ensures that you get multiple alerts for the same group that start
  # firing shortly after another are batched together on the first
  # notification.
  group_wait: 30s

  # When the first notification was sent, wait 'group_interval' to send a batch
  # of new alerts that started firing for that group.
  group_interval: 10s

  # If an alert has successfully been sent, wait 'repeat_interval' to
  # resend them.
  repeat_interval: 3h
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#copilot-arena-alerts'
    send_resolved: false